import type { ReactNode } from "react";
import "./globals.css";
import "./master.css";
import "./aos.css";
// Import plugin styles as needed
import "public/assets/css/plugins/fontawesome.css";
import "public/assets/css/plugins/nice-select.css";

import "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

export const metadata = {
  title: "Tax Consulting || Consultia Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" id="#top">
      <body>{children}</body>
    </html>
  );
}
